# fly.toml app configuration file generated for fetch-assessment on 2023-10-04T17:48:22-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "fetch-assessment"
primary_region = "lax"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
